#!/usr/bin/env python3
# patch51 - Add Component reads like a component list, and the project carries
# the type definitions that make an external VS Code actually know this engine.
import sys, os
ROOT = os.path.dirname(os.path.abspath(__file__))
def rd(p):
    with open(os.path.join(ROOT, p), 'r', encoding='utf-8') as f: return f.read()
def wr(p, s):
    full = os.path.join(ROOT, p); bak = full + '.bak_p51'
    if not os.path.exists(bak):
        with open(bak, 'w', encoding='utf-8') as f: f.write(rd(p))
    with open(full, 'w', encoding='utf-8') as f: f.write(s)
def sub1(t, old, new, what):
    if new in t: print('skip (already applied): ' + what); return t
    if old not in t: print('MISS: ' + what); sys.exit(1)
    if t.count(old) != 1: print('AMBIG %d: %s' % (t.count(old), what)); sys.exit(1)
    return t.replace(old, new)

# ============================ 1. a script component is named like a component
# "NewBehaviour (1).cpp" is a FILE name. Unity lists the class, Godot lists the
# script - neither shows you the extension, and the extension is the one part
# that is never the answer to "which component is this".
s = rd('src/dai_editor_ui.cpp')
s = sub1(s,
"""            if (on_node) continue;
            entries.push_back({ base_of(a), "Scripts", 6, a });""",
"""            if (on_node) continue;
            // Name without the extension, folder in front when it is not at
            // the top: two scripts called "player" in different folders are
            // not the same component, and "player.js" tells you nothing that
            // the icon has not already said.
            std::string b = base_of(a);
            size_t dot = b.find_last_of('.');
            if (dot != std::string::npos && dot > 0) b = b.substr(0, dot);
            std::string dir = parent_of(a);
            if (!dir.empty()) b = base_of(dir) + "/" + b;
            entries.push_back({ b, "Scripts", 6, a });""",
    'script component naming')
wr('src/dai_editor_ui.cpp', s)

# ================================= 2. the typings VS Code needs to be useful
s = rd('examples/editor_demo.cpp')
s = sub1(s,
"""static int         copy_one_file(const char *src, const char *dst);""",
"""static int         copy_one_file(const char *src, const char *dst);
static void        write_editor_support_files();""",
    'typings writer forward decl')

s = sub1(s,
"""static int script_create(const char *name, void *) {""",
"""// ---- what an external editor needs to know about this engine -------------
//
// VS Code is not "integrated" by embedding it - it is Electron, a second
// browser, three hundred megabytes, and it would still not know what
// body.setVel is. What makes an external editor useful is TYPES: a .d.ts
// beside the scripts and a jsconfig that points at it, and suddenly
// completion, hover docs and go-to-definition all work on the engine API,
// with every extension the user already has.
//
// Written on project open, overwritten every time, so the definitions can
// never drift behind the engine that ships them.
static const char *DAIDALOS_DTS =
"// DAIDALOS scripting API - generated by the editor, do not edit.\\n"
"// Every .js in this folder is a behaviour: attach it to an object and the\\n"
"// editor calls init() once and frame() every frame while the game plays.\\n"
"\\n"
"/** The node this script is attached to. */\\n"
"declare const self: number;\\n"
"/** Values the inspector stored for this script's @param fields. */\\n"
"declare const params: { [key: string]: number | string | boolean };\\n"
"/** Host values. state.dt is the length of this frame, in seconds. */\\n"
"declare const state: { dt: number, [key: string]: number | string };\\n"
"declare function print(msg: any): void;\\n"
"\\n"
"declare namespace scene {\\n"
"    /** Node id by name, or -1. */\\n"
"    function find(name: string): number;\\n"
"}\\n"
"\\n"
"declare namespace node {\\n"
"    function getPos(id: number): [number, number, number];\\n"
"    function setPos(id: number, x: number, y: number, z: number): void;\\n"
"    function getRot(id: number): [number, number, number, number];\\n"
"    function setRot(id: number, x: number, y: number, z: number, w: number): void;\\n"
"}\\n"
"\\n"
"declare namespace input {\\n"
"    /** Held? \\\"w\\\", \\\"space\\\", \\\"shift\\\", \\\"left\\\", \\\"a\\\"... */\\n"
"    function key(name: string): boolean;\\n"
"}\\n"
"\\n"
"declare namespace body {\\n"
"    function getVel(id: number): [number, number, number];\\n"
"    function setVel(id: number, x: number, y: number, z: number): void;\\n"
"    function impulse(id: number, x: number, y: number, z: number): void;\\n"
"    function grounded(id: number): boolean;\\n"
"}\\n"
"\\n"
"declare namespace ui {\\n"
"    function text(x: number, y: number, msg: string): void;\\n"
"    function button(label: string): boolean;\\n"
"}\\n";

static const char *DAIDALOS_JSCONFIG =
"{\\n"
"  \\"compilerOptions\\": {\\n"
"    \\"target\\": \\"ES2020\\",\\n"
"    \\"checkJs\\": false,\\n"
"    \\"module\\": \\"none\\"\\n"
"  },\\n"
"  \\"include\\": [\\"**/*.js\\", \\"daidalos.d.ts\\"]\\n"
"}\\n";

static void write_editor_support_files() {
    if (!g_assets_dir[0]) return;
    struct { const char *name; const char *body; } FILES[] = {
        { "daidalos.d.ts", DAIDALOS_DTS },
        { "jsconfig.json", DAIDALOS_JSCONFIG },
    };
    for (const auto &f : FILES) {
        char path[700];
        std::snprintf(path, sizeof(path), "%s/%s", g_assets_dir, f.name);
        FILE *out = std::fopen(path, "wb");
        if (!out) continue;
        std::fwrite(f.body, 1, std::strlen(f.body), out);
        std::fclose(out);
    }
}

static int script_create(const char *name, void *) {""",
    'typings writer')

s = sub1(s,
"""    migrate_scenes_into_assets();
    {
        std::string sd = scene_dir();""",
"""    migrate_scenes_into_assets();
    // The .d.ts and jsconfig.json that make an external editor understand the
    // engine. Written every open so they cannot go stale.
    write_editor_support_files();
    {
        std::string sd = scene_dir();""",
    'call typings writer')
wr('examples/editor_demo.cpp', s)
print('patch51 ok')
