// DAIDALOS scripting API - generated by the editor, do not edit.
// Every .js in this folder is a behaviour: attach it to an object and the
// editor calls init() once and frame() every frame while the game plays.

/** The node this script is attached to. */
declare const self: number;
/** Values the inspector stored for this script's fields. Every top level
    declaration below is one - `let speed = 6` is a field, `let _t = 0` is
    not - and the inspector writes its value straight into the variable
    before init() runs, so reading `params` by hand is never necessary. */
declare const params: { [key: string]: number | string | boolean };
/** Host values. state.dt is the length of this frame, in seconds. */
declare const state: { dt: number, [key: string]: number | string };
declare function print(msg: any): void;

declare namespace scene {
    /** Node id by name, or -1. */
    function find(name: string): number;
}

declare namespace node {
    function getPos(id: number): [number, number, number];
    function setPos(id: number, x: number, y: number, z: number): void;
    function getRot(id: number): [number, number, number, number];
    function setRot(id: number, x: number, y: number, z: number, w: number): void;
}

declare namespace input {
    /** Held? "w", "space", "shift", "left", "a"... */
    function key(name: string): boolean;
}

declare namespace body {
    function getVel(id: number): [number, number, number];
    function setVel(id: number, x: number, y: number, z: number): void;
    function impulse(id: number, x: number, y: number, z: number): void;
    function grounded(id: number): boolean;
}

declare namespace ui {
    function text(x: number, y: number, msg: string): void;
    function button(label: string): boolean;
}
