#!/usr/bin/env python3
"""Pack the SPIR-V shaders into a C++ table so the editor ships as ONE file.

    tools/embed_shaders.py <shaders-dir> <out.cpp>

The renderer still prefers the file on disk (DAI_SHADER_DIR / ./shaders) -
this table is only the fallback when no file exists, so shader overrides
keep working exactly as before.
"""
import os
import sys


def main(argv):
    if len(argv) != 3:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    src, out = argv[1], argv[2]
    names = sorted(f for f in os.listdir(src) if f.endswith(".spv"))
    with open(out, "w", encoding="utf-8") as w:
        w.write("// GENERATED by tools/embed_shaders.py - do not edit.\n")
        w.write('#include "dai_shaders_embed.h"\n\n')
        entries = []
        for n in names:
            sym = "s_" + n.replace(".", "_").replace("-", "_")
            with open(os.path.join(src, n), "rb") as f:
                data = f.read()
            w.write("static const unsigned char %s[] = {\n" % sym)
            for i in range(0, len(data), 16):
                w.write("    " + ",".join("0x%02x" % b for b in data[i:i + 16]) + ",\n")
            w.write("};\n\n")
            entries.append('    { "%s", %s, %d },' % (n, sym, len(data)))
        w.write("const dai_embedded_shader dai_embedded_shaders[] = {\n")
        if entries:
            w.write("\n".join(entries) + "\n")
        w.write("};\n")
        w.write("const int dai_embedded_shaders_count = %d;\n" % len(entries))
    print("embedded %d shaders -> %s" % (len(entries), out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
