#!/usr/bin/env python3
"""Embeds include/dai_native.h into a .cpp so the shipped editor can write it
back out next to a behaviour it is about to compile.

Why this exists: a behaviour is compiled by a compiler on the USER's machine,
against a header that has to match the editor binary exactly. Shipping the
header as a loose file means it can be deleted, edited or left behind by an
update, and the mismatch shows up as a crash inside a .dll rather than an
error. The binary that defines the ABI is the binary that writes the header.
"""
import sys, os

src = sys.argv[1] if len(sys.argv) > 1 else 'include/dai_native.h'
dst = sys.argv[2] if len(sys.argv) > 2 else 'build/dai_native_header.cpp'

with open(src, 'rb') as f:
    data = f.read()

os.makedirs(os.path.dirname(dst) or '.', exist_ok=True)
out = ['// Generated by tools/embed_native.py - do not edit.\n',
       '#include <stddef.h>\n\n',
       'extern "C" const char *dai_native_header_text(void) {\n',
       '    static const char TEXT[] = {\n']
line = '        '
for i, b in enumerate(data):
    line += '%d,' % b
    if len(line) > 92:
        out.append(line + '\n')
        line = '        '
out.append(line + '0\n')
out.append('    };\n    return TEXT;\n}\n')

with open(dst, 'w') as f:
    f.write(''.join(out))
print('-- embedded %s (%d bytes) -> %s' % (src, len(data), dst))
