#!/usr/bin/env python3
"""Generates TypeScript declarations for the WebAssembly build.

Hand written .d.ts files rot the moment the C API changes. This one is
generated from the same table the build uses to export the functions, so a
signature can only drift if someone edits both.

  python3 tools/gen_dts.py build/web/daidalos.d.ts
"""
import sys

# name -> (return type, [(arg name, ts type)]), matching tools/web_api.cpp
API = [
    ("dai_web_create", "number", [("backend", "number"), ("tickHz", "number"),
                                  ("maxBodies", "number"), ("seed", "number")],
     "Creates a world and returns its pointer. backend 0 = Jolt, 1 = null."),
    ("dai_web_destroy", "void", [("world", "number")], "Frees the world."),
    ("dai_web_body", "number", [("world", "number"), ("shape", "number"), ("motion", "number"),
                                ("hx", "number"), ("hy", "number"), ("hz", "number"),
                                ("px", "number"), ("py", "number"), ("pz", "number"),
                                ("density", "number"), ("userData", "number")],
     "Creates a body and returns its handle. shape 0=box 1=sphere 2=capsule, motion 0=static 1=kinematic 2=dynamic."),
    ("dai_web_impulse", "number", [("world", "number"), ("body", "number"),
                                   ("x", "number"), ("y", "number"), ("z", "number")],
     "Applies an impulse. Returns a dai_result code."),
    ("dai_web_step", "void", [("world", "number"), ("ticks", "number")],
     "Advances the simulation by whole ticks."),
    ("dai_web_tick", "number", [("world", "number")], "Current tick number."),
    ("dai_web_checksum", "string", [("world", "number")],
     "State checksum as a 16 character hex string - 64 bits do not fit in a JS number."),
    ("dai_web_transforms", "number", [("world", "number"), ("alpha", "number")],
     "Fills the shared transform buffer and returns the body count. alpha 0..1 interpolates between ticks."),
    ("dai_web_transform_ptr", "number", [],
     "Pointer into HEAPF32 for the buffer filled by dai_web_transforms. 9 floats per body: handle, userData, x, y, z, qx, qy, qz, qw."),
    ("dai_web_input", "void", [("world", "number"), ("player", "number"), ("tick", "number"),
                               ("axis0", "number"), ("axis1", "number"), ("buttons", "number")],
     "Queues input for a tick. Feed inputs as the simulation advances, not thousands of ticks ahead."),
    ("dai_web_rollback", "number", [("world", "number"), ("tick", "number")],
     "Rolls back to a tick and re-simulates to the present. Returns a dai_result code."),
    ("dai_web_body_count", "number", [("world", "number")], "Number of live bodies."),
    ("dai_web_version", "string", [], "Engine version string."),
]

out = ["// Generated by tools/gen_dts.py - do not edit.",
       "// The C API lives in tools/web_api.cpp; this file mirrors it.",
       "",
       "export interface DaidalosModule {",
       "  /** Emscripten heap view. Transforms are read from here. */",
       "  HEAPF32: Float32Array;",
       "  ccall(name: string, returnType: string | null, argTypes: string[], args: any[]): any;",
       "  cwrap(name: string, returnType: string | null, argTypes: string[]): (...args: any[]) => any;",
       "  UTF8ToString(ptr: number): string;",
       ""]

for name, ret, args, doc in API:
    sig = ", ".join(f"{a}: {t}" for a, t in args)
    out.append(f"  /** {doc} */")
    out.append(f"  _{name}({sig}): {ret if ret != 'string' else 'number'};")

out += ["}",
        "",
        "/** Loads the WebAssembly module. */",
        "declare function Daidalos(options?: Record<string, unknown>): Promise<DaidalosModule>;",
        "export default Daidalos;",
        "",
        "/** Typed wrapper around the raw exports. */",
        "export declare class World {",
        "  constructor(module: DaidalosModule, options?: { backend?: number; tickHz?: number; maxBodies?: number; seed?: number });",
        "  createBody(o: { shape?: number; motion?: number; half?: [number, number, number];",
        "                  position?: [number, number, number]; density?: number; userData?: number }): number;",
        "  step(ticks?: number): void;",
        "  /** Zero copy view of the transform buffer: 9 floats per body. */",
        "  transforms(alpha?: number): Float32Array;",
        "  readonly tick: number;",
        "  readonly checksum: string;",
        "  destroy(): void;",
        "}",
        ""]

path = sys.argv[1] if len(sys.argv) > 1 else "build/web/daidalos.d.ts"
open(path, "w").write("\n".join(out))
print("wrote", path, len(out), "lines")
