#pragma once
// The shader table generated by tools/embed_shaders.py. Files on disk win
// (DAI_SHADER_DIR / ./shaders) - this is the fallback that lets the editor
// run as ONE portable .exe with nothing installed beside it.
struct dai_embedded_shader { const char *name; const unsigned char *data; unsigned int size; };
extern const dai_embedded_shader dai_embedded_shaders[];
extern const int dai_embedded_shaders_count;
